### ISSUE TITLE
MakeColor panics when alpha is 0

### ISSUE THREAD

**Issue by mikegleasonjr** [lucasb-eyer/go-colorful#21]
Because when `a` is zero, a division by 0 occurs.

**Comment by lucasb-eyer** [comment]
Ouch, you are right. And it's actually undefined what should be done in that case, as the original RGB values have been lost in the alpha pre-multiplication at that point.

I'm not sure what the right call is here. Either return an error and let the user handle it, or default to black, or to a user-specified default value. Thoughts?

**Comment by mikegleasonjr** [comment]
I really don't know how to handle this to be honest.

**Comment by lucasb-eyer** [comment]
I'll leave this issue open until someone comes up with a good suggestion, meanwhile I'll add an entry to the FAQ in the README, linking here.

**Comment by lucasb-eyer** [comment]
Yeah these are the two only remotely sensible options, but neither is truly satisfying. The error return would be inconvenient as most people would probably just set it to all-zero, but at least it would force that decision on the user.

How about setting them to 0 (since that's the limit they converge to as alpha goes to 0) *and* having an ok/error return value, which can be ignored if the default all-zero is desired, but which would have the user at least partially think about it. What do you think?

I'd be happy to accept a PR that also adds a test and updates the README in the corresponding places.
