### ISSUE TITLE
Does SoftPaletteEx also ensure uniquiness of the colors in the palette?

### ISSUE THREAD

**Issue by maxiride** [lucasb-eyer/go-colorful#29]
Hi, I found this package while searching how to generate palettes, however, I need to ensure that the colors in a palette are all unique.

It is unclear to me whether the method takes care of this or not.

**Comment by Maxiride** [comment]
An attempt I leave here for [reference](https://pastebin.com/6Tnt3zsq)

**Comment by lucasb-eyer** [comment]
Hi,

### Uniqueness of colors

Yes, this is actually the point of this function: creating unique, as distinct as possible colors. If I remember correctly, you should only get two identical colors if you ask for a palette so large that there is no other choice. But I think the unit-tests don't actually verify this, so there may still be bugs. Actually, a unit-test verifying this would be nice to have.

### Your code to show palettes

I guess you didn't see [doc/palettegens/palettegens.go](https://github.com/lucasb-eyer/go-colorful/blob/master/doc/palettegens/palettegens.go), which is the code that generated the following image from the README:

![palettes](https://github.com/lucasb-eyer/go-colorful/raw/master/doc/palettegens/palettegens.png)

As now I see the file isn't mentioned in the README. I'll fix that.

Regarding Go, I don't feel I can comment as I haven't written Go for quite a few years and am not up-to-date anymore myself :smile:

**Comment by Maxiride** [comment]
> creating unique, as distinct as possible colors. If I remember correctly, you should only get two identical colors if you ask for a palette so large that there is no other choice.

I checked the `palettegens.go` code however I can't see where you check if a color has already been generated. The isBrowny function only checks if the color falls in the crieteria. Could you point me in the right direction in the code where you check if a color has already been generated?

**Comment by lucasb-eyer** [comment]
Yeah, there is no explicit check, and there is no point in having one.

Let me try to explain the algorithm, with links to the relevant code:

1. [Create a uniform grid of points covering the whole color-space.](https://github.com/lucasb-eyer/go-colorful/blob/master/soft_palettegen.go#L51-L60)
2. [Optionally, keep only those which pass the user-specified test (such as `isBrowny`).](https://github.com/lucasb-eyer/go-colorful/blob/master/soft_palettegen.go#L55)
3. [Select random initial colors out of these samples, but make sure they are unique](https://github.com/lucasb-eyer/go-colorful/blob/master/soft_palettegen.go#L71-L75).
4. [Run K-Means with these initial colors as initial cluster centers](https://github.com/lucasb-eyer/go-colorful/blob/master/soft_palettegen.go#L81-L147). The K-Means is a little more involved than standard K-means because:
4.1. [If a cluster is empty, it re-seeds the cluster using a unique color](https://github.com/lucasb-eyer/go-colorful/blob/master/soft_palettegen.go#L119-L124). (Empty cluster could happen due to special color `check` treatment.)
4.2. [It also makes sure the cluster means are always valid colors (according to `check`) and if they aren't, use the closest valid color instead, but again making sure the closest valid color is not a duplicate.](https://github.com/lucasb-eyer/go-colorful/blob/master/soft_palettegen.go#L127-L145)

If you don't know K-means in depth, you might want to read upon it first. It is not obvious, but I'm relatively confident this algorithm doesn't produce duplicates in all reasonable use-cases. Did you actually encounter duplicates, or are you just generally curious about it?
