### ISSUE TITLE
colorful and lightbulbs

### ISSUE THREAD

**Issue by daenney** [lucasb-eyer/go-colorful#35]
This is more of a request for help than an issue.

I'm working on some home automation that involves light bulbs! These light bulbs are documented to support CIE xy and a brightness value. Their x and y values range from 0-65535 and brightness goes from 1 to 254. This seems a lot like CIE-xyY assuming I can just convert the numbers to be in the 0..1 range? But maybe it's XYZ? Not sure what the difference is here. I'm mostly confused about the brightness aspect b/c helpfully no explanation is ever given about how that one fits in.

Due to $reasons I also need to get a hue saturation brightness representation of this. Hue in this case is documented as degrees 0-360, so that sounds like a color wheel, whereas saturation is documented as a percentage 0-100 and brightness is equally a 0-100 percentage. This sounds like CIE-L*C*h° to me, at least the h lines up, but unsure how L* and C* would map in this case?

I'm rather confused at this point, so any pointers as to what I'm misunderstanding, or what to read, would be greatly appreciated.

**Comment by KelSolaar** [comment]
@daenney : If you were to share the documentation of your light bulbs it would maybe help.

> This seems a lot like CIE-xyY assuming I can just convert the numbers to be in the 0..1 range?

Yes but it is likely that being 8-bit encoded the so-called *brightness* value is non-linearly encoded, i.e. it has some sort of transfer function applied. Nobody sane would store radiometrically linear data in a 8-bit container. 

I would think that your given x and y coordinates are effectively CIE xy chromaticity coordinates and that brightness is maybe the Lightness from CIE LCHab or the pseudo-lightness value of one of the HSV/HSL/HSB colourspace.

> I'm rather confused at this point, so any pointers as to what I'm misunderstanding

You are not misunderstanding anything, you are just paying the price for incorrect terminology and incorrect encoding specification. Have you thought about contacting the vendor for clarification?

**Comment by daenney** [comment]
> @daenney : If you were to share the documentation of your light bulbs it would maybe help.

The best I can do is the Philips Hue developer docs, specifically about the lights. Unfortunately there's very little documentation about the bulbs themselves, but here's what I got w.r.t the colour bulbs:

```

bri | uint8 | Brightness of the light. This is a scale from  the minimum brightness the light is capable of, 1, to the maximum  capable brightness, 254.
hue | uint16 | Hue of the light. This is a wrapping value  between 0 and 65535. Note, that hue/sat values are hardware dependent  which means that programming two devices with the same value does not  garantuee that they will be the same color. Programming 0 and 65535  would mean that the light will resemble the color red, 21845 for green  and 43690 for blue.
sat | uint8 | Saturation of the light. 254 is the most saturated (colored) and 0 is the least saturated (white).
xy | list 2..2 of float 4 | The x and y coordinates of a color in CIE color space. The first entry is the x coordinate and the second entry is the y  coordinate. Both x and y are between 0 and 1. Using CIE xy, the colors  can be the same on all lamps if the coordinates are within every lamps  gamuts (example: “xy”:[0.409,0.5179] is the same color on all lamps). If  not, the lamp will calculate it’s closest color and use that. The CIE  xy color is absolute, independent from the hardware.
```

There's also something else specific they mention, in that the lights are specified as a "Gamut B', which they identify as:
```
Color | x | y
Red | 0.675 | 0.322
Green | 0.409 | 0.518
Blue | 0.167 | 0.04
```

They also have a conversion table that might shed some light, for their Gamut B:
```
Hue | Final-X | Final-y
0 | 0.3972 | 0.4564
12750 | 0.5425 | 0.4196
25500 | 0.41 | 0.51721
46920 | 0.1691 | 0.0441
56100 | 0.4149 | 0.1776
65280 | 0.6679 | 0.3181
```

And this diagram gets involved too
![colorspace](https://developers.meethue.com/wp-content/uploads/2018/02/color.png)

Philips defines x,y that way, whereas Ikea (which is part of what I'm trying to convert to/from) seem to just take 0-65535 for x and y without specifying much of anything.

I captured a few color values on the Ikea bulb, and red at full brightness gets me this:

```
brightness: 254,
color_x: 42926,
color_y: 21299,
```
Dimming the light only affects the brightness value

```
brightness: 33,
color_x: 42926,
color_y: 21299,
```

There's a lot of related code in different smart home packages that relate to CIE <-> HSB conversion but it's all terribly lacking in docs. It just kinda happens. Perhaps the most interesting bit is this one: https://github.com/hreichert/smarthome/blob/2979e2028b2534f2049177565406df717cdfd198/extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/internal/TradfriColor.java#L84-L184

I don't know if any of this helps.

**Comment by daenney** [comment]
It seems that what Ikea and Philips do is CIE XYZ, with Z being the brightness. Which I can then convert to RGB and can then get me to HSV

**Comment by KelSolaar** [comment]
@daenney :

`X` and `Y` in `CIE XYZ` are absolutely not the same than `x`, `y` in `CIE xyY`.

I would not rely excessively on the Java code you linked as there are a lot of undocumented assumptions going there: 

- Where is the [CIE XYZ to RGB](https://github.com/hreichert/smarthome/blob/2979e2028b2534f2049177565406df717cdfd198/extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/internal/TradfriColor.java#L101) matrix coming from?
- Why is the [sRGB encoding commented](https://github.com/hreichert/smarthome/blob/2979e2028b2534f2049177565406df717cdfd198/extensions/binding/org.eclipse.smarthome.binding.tradfri/src/main/java/org/eclipse/smarthome/binding/tradfri/internal/TradfriColor.java#L122)?

This leads me to the following question: what are you trying to achieve specifically? Reading your second answer it seems like you are trying to come up with a unified interface to talk to different vendor light bulbs.

Using `CIE xyY` (or `CIE XYZ`) as a colourspace to unambiguously specify your colour values is a good idea. For the Philips Hue, the harder part is finding how the *Brightness* parameter is encoded. I have seen the assumption that gamma 2.2 is used to encode it non-linearly, at which point you could consider it to be the Luminance `Y` of `CIE xyY`. Alternatively, you could measure it with a light meter by doing a value wedge or similarly a photographic wedge at fixed photographic exposure values.

The Ikea ones seem to be working similarly so no big issue because you can use `xy` chromaticity coordinates and a *Brightness* parameter.

Not sure about Apple ones, I would be surprised if you cannot specify `xy` chromaticity coordinates or if there is not a way to go back to them.

Once you can specify your values with `CIE xyY`, and assuming you have a bit of colorimetric data for the bulbs gamut you should be able to drive them in a unified way.

Here is an exampe diagram with some typical conversion paths:

![image](https://user-images.githubusercontent.com/99779/56463274-f3006380-6424-11e9-96dd-7a74150deb6d.png)

**Comment by daenney** [comment]
>  Reading your second answer it seems like you are trying to come up with a unified interface to talk to different vendor light bulbs.

Yes, exactly that. I have devices on all 3 ecosystems and I'd like to be able to build a thing where specifying a color gets correctly translated to the different bulbs, essentially allowing me to mostly color coordinate independent of manufacturer.

> I have seen the assumption that gamma 2.2 is used to encode it non-linearly, at which point, upon decoding, you could consider it to be the Luminance Y of CIE xyY

I'm not quite sure I understand this? What do you mean when you say "gamma 2.2 is used to encode it non-linearly"?

> Not sure about Apple ones, I would be surprised if you cannot specify xy chromaticity coordinates or if there is not a way to go back to them.

So Apple pretty much only gives me HS(V/B). That's the only characteristics they expose for a color bulb so that's all you have to work with. They don't support CIE xy at all.

**Comment by KelSolaar** [comment]
> essentially allowing me to mostly color coordinate independent of manufacturer.

Important question here then: what level of accuracy are you trying to achieve and are you willing to pour a bit of money into the project? If yes, then I would certainly try to rent a colorimeter, e.g. https://c800.sekonic.com/ or a spectrometer of any kind to perform measurements.

> I'm not quite sure I understand this? What do you mean when you say "gamma 2.2 is used to encode it non-linearly"?

Because of quantization issues, a 8-bit container is unsuitable to store linear data, in order to produce a perceptually uniform output without mach bands/contouring/quantization defects, one needs to non-linearly encode its linear signal before storing it in a 8-bit container. This is valid for images and you might have heard about *gamma correction* or (horribly) labelled functions such as `sRGB to linear` or `linear to sRGB`. Those principles are valid for any signal, as an example, if your lights did not have non-linear encoding of the *Brightness* value, you would probably see its perceived brightness jumping at low Luminance values each time you were to increase it by one code value.

> So Apple pretty much only gives me HS(V/B).

Yeah this is bad! You would need to come up with a mapping from input/output measurements.

**Comment by daenney** [comment]
> Important question here then: what level of accuracy are you trying to achieve and are you willing to pour a bit of money into the project?

Given the amount of hardware already involved, sure. I'm mostly looking to get to a point where perceived colour will be roughly the same. It's not likely to ever be exact once bulbs of different manufacturers get involved too since different bulbs appear to support different ranges.

> Because of quantization issues, a 8-bit container is unsuitable to store linear data. In order to produce a perceptually uniform output without mach bands/contouring/quantization defects, one needs to non-linearly encode its linear signal before storing it in a 8-bit container. This is valid for images and you might have heard about gamma correction or (horribly) labelled functions such as sRGB to linear or linear to sRGB. Those principles are valid for any signal, as an example, if your lights did not have non-linear encoding of the Brightness value, you would probably see its perceived brightness jumping at low Luminance values each time you were to increase it by one code value.

Thanks for the explanation. But I'm afraid that just completely flew over my head :sweat_smile:. I'll search around a bit, see if I can find some math that explains this.

Thanks a lot for taking the time to explain all of this. It's really awesome.

**Comment by KelSolaar** [comment]
> It's not likely to ever be exact once bulbs of different manufacturers get involved too since different bulbs appear to support different ranges.

Yes, they will all have very different gamuts but you might be able to find a good middle ground for all of them, to me given what you described the hard part is to figure out the Apple HSV <--->  CIE xyY mapping.

> Thanks a lot for taking the time to explain all of this. It's really awesome.

You are welcome, feel free to ask any other questions!

**Comment by daenney** [comment]
I think this is breaking my brain. I tried a few things to get a sense of what's going on with the Ikea bulb but it almost feels like it's made it worse. Ikea lets me set `xy` or `hs` and brightness. However, whatever I do for `hs` and `xy` brightness is never affected, it always returns the same value. This doesn't seem possible? If I tweak the brightness the bulb just dims, kind of expected.

The "bluest blue" according to my perception I've been able to configure on the bulb is `x: 9710` and `y: 1789` which would give me `[0.14817, 0.0273]`. This is with the bulb at full brightness, so 254 whatever that means. This makes the bulb return `hue: 45840` and `sat: 65279`. It'll never go over 65279 for `sat`, try anything higher and the bulb flips to its error state. If I now dim the bulb, set `brightness: 127` the `xy` and `hs` values don't change.

Now the fun bit, I can go much lower than `x: 9710`, for example if I try `x: 6300` that gives me `x: 0.09613`, with a `y: 1789` that would still be `0.0273` which seems to fall outside of the map. The bulb accepts the command though, but instead I get a `h: 43519` returned now, `sat` is still `65279`. I'm assuming this happens b/c the bulb tried to find the closest match it could, but unfortunately just echos back the `x` and `y` values instead of recalculating them. Unfortunately when I set the same `h` and `s` values on the bulb the `x` and `y` values aren't modified, so I can't see what it would match to.

So how do I normalize this?

Tweaking the brightness of the bulb does not seem to have an impact on XY or HS, at least as reported by the device. It obviously does have an impact on my perception since the bulb is less "bright" (not sure what the right word for this is).

This would almost seem to suggest that I should use a static value for the Y in xyY, when I'm trying to create a `color.Color` based on those?

**Comment by daenney** [comment]
So far the closest I seem to get is `colorful.Xyz(x, y, 1-x-y).Clamped()`. Taking the hex of that seems to match fairly closely but it's off by a bit. The green is a lot more dirty.

**Comment by daenney** [comment]
Based on that bluest blue...

H: (45840/65535) * 360 = 251.8105
S: (65279/65535) = 0.9961
V: 1

x = 0.158579
y = 0.064862
Y =  0.079431

The bulb gives me:
x = 9710 / 65535 = 0.14817
y = 1789 / 65535 = 0.0273

I'm clearly off here, but I don't know why.

**Comment by KelSolaar** [comment]
> However, whatever I do for hs and xy, the brightness is never affected, it always returns the same value.

Well that is expected behaviour, `xy` chromaticity coordinates (and hue/saturation) are independent of Luminance (or *Lightness/Brightness*) by design. `CIE xyY` is a projective transformation of `CIE XYZ` along the Luminance axis `Y` so that Luminance can be dealt with separately. This is effectively what makes the CIE 1931 Chromaticity Diagram:

![image](https://user-images.githubusercontent.com/99779/56497878-78823180-6553-11e9-997e-3c35da78654a.png)

When you cherry-pick a `xy` chromaticity coordinate, you are choosing a point on this particular chromaticity diagram, but that point has no Luminance information, this is something you have to give separately.

> I do have a colorimeter at home, but not a spectrometer. I don't suppose I can apply that somehow?

I would probably try to measure the primaries of your lights, i.e. the pure Red, Green and Blue coordinates so that you can build their gamut, knowing that you will be able to do the conversions.

**Comment by daenney** [comment]
Awesome, so it seems I'm mostly there. I have the conversions working and it's pretty close now. I've kind of had to eye-ball the gamut, which isn't great. I'll try with a colorimeter, see what I get.

It does feel a little wrong though to go from `hsv`, with `v` pinned at `1` to `xyY` and then discard the `Y`. It seems extremely lossy but I don't imagine there's a way to avoid that given what I currently know and the fact that I have to convert between them due to manufacturers doing different things.

**Comment by daenney** [comment]
I did some measurements with the colorimeter. Got me both XYZ and Yxy. Given I have no `Y` to reference when it comes to these bulbs, do I simply discard it? That seems wrong but I'm not sure what to do with it. Can I do something more sensible based on XYZ instead?

**Comment by KelSolaar** [comment]
The `Y` (Luminance) in `CIE XYZ` and `CIE xyY` is the same. I would be useful to measure at various *Brightness* values what the actual Luminance is so that you can find what the relationship is with input. Would help to determine if it follows a power law or any non-linear curve.

**Comment by daenney** [comment]
Thanks! I'll give that a go. Either way it shouldn't affect the xy values right? As in it doesn't impact the gamut.

**Comment by KelSolaar** [comment]
Correct!

**Comment by daenney** [comment]
It turns out reading the ZigBee spec, and specifically the bits about colour control, has proven to be fairly enlightening :bulb:. Confirms what we already knew but when manufacturers say CIE xy what they indeed mean is CIE xyY, so says the spec.

I also discovered this:

```
* u16ColourPointRX is the value for the chromaticity x for the red colour point
of the device, as defined in the CIE xyY colour space, in the range 0-65279.
The normalised value of x is calculated using the following formula:
x = u16ColourPointRX/65536.
* u16ColourPointRY is the value for the chromaticity y for the red colour point
of the device, as defined in the CIE xyY colour space, in the range 0-65279.
The normalised value of y is calculated using the following formula:
y = u16ColourPointRY/65536.
* u8ColourPointRIntensity is a representation of the relative intensity of
the red colour point of the device, normalised such that the colour point with the
highest relative intensity has the value 0xFE (the value 0xFF indicates an
invalid value).
```

I assume what they're calling intensity here is our Y. It seems that they've reduced the space of CIE xy a bit, with nothing being able to exceed 65279, I can't get past 0.9961 on x or y. That's still plenty but it seems a bit odd they wouldn't just stick to 1.

What I'm wondering about is what they mean with this:
> normalised such that the colour point with the highest relative intensity has the value 0xFE (the value 0xFF indicates an invalid value).

The highest relative intensity?

**Comment by daenney** [comment]
I've managed to find the brightness curve. Apparently we get to 1-254 based on the following formula:
`%light = 10 ^ ((level - 1) / (253 / 3))-1`

**Comment by KelSolaar** [comment]
Sorry for the late answer, been extremely busy lately, where did you find this curve? It is quite unusual: https://www.wolframalpha.com/input/?i=10%5E(((x-1)%2F(253%2F3))-1)

```python
Python 3.7.1 | packaged by conda-forge | (default, Mar 13 2019, 05:40:40)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> f = lambda x: 10 ** ((x - 1.0) / (253.0 / 3.0)) - 1.0
>>> f(254)
999.0
>>> f(1)
0.0
```

**Comment by daenney** [comment]
ZigBee spec. It's the dimming curve for lights: http://www.zigbee.org/wp-content/uploads/2014/10/07-5123-06-zigbee-cluster-library-specification.pdf. Chapter 5 heading 3 subsection 4.

I agree it feels a little extreme.
