### ISSUE TITLE
would be nice to sponsor you

### ISSUE THREAD

**Issue by gdamore** [lucasb-eyer/go-colorful#47]
I've received sponsorships for work that I developed using go-colorful, and it would be nice to share the love, even just a bit.  If you set up a go sponsorship, I'll arrange to pass a portion of my sponsorship proceeds to you.

**Comment by makeworld-the-better-one** [comment]
Hello @gdamore, glad to hear it!

Lucas has passed maintenance of this repo on to me. We have decided on a 50/50 split of the sponsorship, is that possible to do from your end?

I am a member of the GitHub Sponsors [program](https://github.com/sponsors/makeworld-the-better-one), and I also have a [Ko-Fi](https://ko-fi.com/makeworld), I hope either of those will work.

@lucasb-eyer will comment in the thread to confirm all this.

**Comment by lucasb-eyer** [comment]
Thanks for your generous thought, and happy go-colorful was useful to you!

Since I have not been actively coding in golang for a couple years now, it makes sense that someone who actively uses the library and has an interest in it continues maintenance, i.e. @makeworld-the-better-one .

I'm now setting up GitHub sponsors account and indeed ideally we split half-half.

**Comment by gdamore** [comment]
I will take a look at this shortly.  Stay tuned.

Get Outlook<https://aka.ms/qtex0l> for iOS
________________________________

**Comment by lucasb-eyer** [comment]
I just created a FUNDING.yml file for the project, but unfortunately it will just list the two of us, doesn't seem to have any automatic split functionality. How non-fancy! :) Let me know if you need anything else.

**Comment by gdamore** [comment]
So I've sponsored you both.  Thanks for your work!
